server:
  port: 8090
spring:
  data:
    mongodb:
      host: localhost
      username: admin
      password: admin
      port: 27017
      database: customer
      authentication-database: admin