spring.application.name=gateway-service
spring.config.import=optional:configserver:http://localhost:8888
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
management.appoptics.metrics.export.api-token=